models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

controllers/LoginController.php
<?php

namespace app\controllers;

use app\models\DevUsers;
use yii\web\Controller;
use Exception;
use Yii;

class LoginController extends Controller
{

    public $layout = false;

    public function actionIndex()
    {
        Yii::$app->view->title = 'Admin管理系统';
        $host = Yii::$app->request->getAbsoluteUrl();//绝对路径
        return $this->render('index', [
            'host' => $host
        ]);
    }

    /**
     *  用户登录
     * @return object
     * @throws Exception
     */
    public function actionLogin()
    {

        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');

        $username = trim($username);
        $password = trim($password);

        $hash_password = Yii::$app->security->generatePasswordHash($password);//加密

        Yii::debug('--hash--' . $hash_password, __METHOD__);

        $justifyPwd = Yii::$app->security->validatePassword($password, $hash_password);//校验


        $user = DevUsers::findOne([
            'username' => $username,
        ]);

        if ($user) {
            //有该用户且通过密码校验
            if ($user['password'] == $password && $justifyPwd) {
                DevUsers::updateAll(
                    [
                        'lastvisit_ip' => Yii::$app->request->getUserIP(),
                        'lastvisit_time' => time(),
                        'login_count' => $user->login_count + 1,//登录次数+1
                    ],[
                    'username' => $username,
                    'id' => intval($user['id'])
                ]);
                return Yii::createObject([
                    'class' => 'yii\web\Response',
                    'format' => \yii\web\Response::FORMAT_JSON,
                    'data' => [
                        'message' => '登录成功',
                        'code' => 100,
                    ]
                ]);
            } else {
                //有该用户但是密码没有通过验证
                return Yii::createObject([
                    'class' => 'yii\web\Response',
                    'format' => \yii\web\Response::FORMAT_JSON,
                    'data' => [
                        'message' => '密码错误',
                        'code' => -101,
                    ]
                ]);
            }

        }


        //认为是第一次登录
        $user_data = [
            'username' => $username,
            'password' => $password,
            'salt' => '',
            'status' => 1,
            'register_ip' => Yii::$app->request->getUserIP(),
            'register_time' => time(),
            'lastvisit_time' => time(),
            'lastvisit_ip' => Yii::$app->request->getUserIP(),
        ];

        $user = new DevUsers();
        $user->attributes = $user_data;
        $user->save(false);

        return Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => \yii\web\Response::FORMAT_JSON,
            'data' => [
                'message' => '登录成功',
                'code' => 101,
            ]
        ]);
    }

}

views/login/index.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;
use app\assets\ElementUI;

ElementUI::register($this);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="<?=$host  ?>/favicon.ico" type="image/x-icon"/>
    <?php $this->head() ?>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        #app, body, html {
            height: 100%;
            width: 100%;
        }
        body {
            background-color: #f2f2f2;
            overflow-y: hidden;
        }

        .login {
            background-image: url("<?php $host ?> /images/bg.png");
            width: 100%;
            background-position: 50%;
            background-size: cover; /*铺满*/
            background-repeat: no-repeat;
            height: 100%;
            position: relative;
        }

        .login-box {
            color: #ffffff !important;
            position: relative;
            transform: translateY(-60%);
            right: 35px;
            top: 50%;
            margin: 0 auto;
            width: 300px;
        }

        .user-login-form {
            position: relative;
            right: 20px;
            top: 20px;
        }
        .user-login-header {
            position: relative;
            right: -30px;
            padding: 15px;
        }

        .login-btn {
            position: relative;
            width: 300px;
        }

        .dev-process {
            display: none;
            position: relative;
            width: 150px;
            left: 30px;
            top: 40%;
        }

        .el-form-item__label {
            color: #ffffff;
        }

    </style>
</head>
<body>
<?php $this->beginBody() ?>
<div id="app">
    <div class="login">
        <div class="login-box">
            <template>
                <div class="user-login-header">
                    <h2>Element-ui-Admin</h2>
                    <p>基于Vue+Element-ui实现的后台管理系统</p>
                </div>
            </template>
            <template>
                <div class="user-login-form">
                    <el-form :model="loginForm" status-icon :rules="loginRules" ref="loginForm" label-width="100px">
                        <el-form-item label="账号" prop="username">
                            <el-input type="text" v-model="loginForm.username" autocomplete="off"></el-input>
                        </el-form-item>
                        <el-form-item label="密码" prop="password">
                            <el-input type="password" v-model="loginForm.password" autocomplete="off"></el-input>
                        </el-form-item>
                        <el-form-item label="确认密码" prop="checkPass">
                            <el-input type="password" v-model="loginForm.checkPass"></el-input>
                        </el-form-item>
                        <div class="login-btn">
                            <el-form-item>
                                <el-tooltip class="item" effect="dark" :content="loginTip" placement="bottom">
                                    <el-button type="primary" @click="submitForm('loginForm')">登录</el-button>
                                </el-tooltip>
                                <el-button @click="resetForm('loginForm')">重置</el-button>
                            </el-form-item>
                        </div>
                    </el-form>
                </div>
            </template>
        </div>
        <div class="dev-process" >
            <template>
                <el-tooltip class="item" effect="light" :content="tooltip" placement="top-start" width="150px">
                    <el-progress type="circle" :percentage="percentage" stroke-width="8"></el-progress>
                </el-tooltip>
            </template>
        </div>

    </div>
</div>
<script>
    axios.defaults.baseURL = "";
    const router = new VueRouter({
        routes: [
            {path : '/site',  name: 'indexPage'},
        ]
    });

    new Vue({
        el: '#app',
        router,
        data() {
            //定义校验规则 validate
            var validateUsername = (rule, value, callback) => {
                if (value === '') {
                    callback(new Error('请输入账号'));
                } else if (value.length < 5) {
                    callback(new Error('账号不能少于六位数'));
                    //todo  可以加正则匹配 账号只能是字母+数字组合
                } else {
                    //todo 规则
                    callback();
                }
            };
            var validatePassword= (rule, value, callback) => {
                if (value === '') {
                    callback(new Error('请输入密码'));
                } else {
                    if (this.loginForm.checkPass !== '') {
                        this.$refs.loginForm.validateField('checkPass');
                    }
                    callback();
                }
            };
            var validateCheckPass = (rule, value, callback) => {
                if (value === '') {
                    callback(new Error('请再次输入密码'));
                } else if (value !== this.loginForm.password) {
                    callback(new Error('两次输入密码不一致!'));
                } else {
                    callback();
                }
            };
            return {
                loginForm: {
                    username: '',
                    password: '',
                    checkPass: ''
                },
                loginTip: '为了方便演示，用户名与账号可随意登录',
                tooltip: '当前开发进度为5%',
                percentage: '5',
                //校验规则
                loginRules: {
                    username: [
                        {
                            validator: validateUsername,
                            trigger: 'blur'
                        }
                    ],
                    password: [
                        {
                            validator: validatePassword,
                            trigger: 'blur'
                        }
                    ],
                    checkPass: [
                        {
                            validator: validateCheckPass,
                            trigger: 'blur'
                        }
                    ],
                }
            };
        },
        methods: {
            //登入成功提示
            loginSuccess() {
                this.$notify({
                    title: '登入成功',
                    message: '后台正在开发中~敬请期待~',
                    type: 'success'
                });
            },

            alertMessage(msg,close,type) {
                this.$message({
                    showClose: close,
                    message: msg,
                    type: type
                });
            },

            //进入系统页提示
            initTip() {
                this.$notify({
                    title: '温馨提示',
                    message: '为了方便演示,用户名与密码可随意输入',
                    type: 'success'
                })
            },
            //提交表单
            submitForm(formName) {
                // let formData = this.loginForm;
                //formData = JSON.stringify(formData);
                let loginUrl = '<?php echo \yii\helpers\Url::toRoute('login/login');?>';
                const postdata = {
                    username: this.loginForm.username,
                    password: this.loginForm.password,
                };
                this.$refs[formName].validate((valid) => {
                    if (valid) {
                        console.log('res', valid)
                        //todo  接口
                        console.log('--登录接口--')
                        let param = new URLSearchParams();
                        param.append('username', postdata.username);
                        param.append('password', postdata.password);
                        axios.post(loginUrl, param)
                            .then(response => {
                                console.log('success', response);
                                if(response.data.code === 100){
                                    this.loginSuccess();
                                     // this.$router.push({path:'site/index'});
                                     // window.location.href = 'http://binzhizhu.top';
                                    let link = '<?php echo \yii\helpers\Url::to(['site/index'])?>';
                                    window.location.href = link;
                                }else if (response.data.code= -101){
                                    this.alertMessage('密码错误',true,'error');
                                }
                            })
                            .catch(error => {
                                console.log(error)
                            });
                    } else {
                        console.log('res', valid)
                        console.log('--data--',postdata)

                        return false;
                    }
                });
            },
            //重置表单 移除校验结果
            resetForm(formName) {
                this.$refs[formName].resetFields();
            }
        }
    });
</script>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>